### ISSUE TITLE
MainActivity Crash in Redmi Note 3

### ISSUE THREAD

**Issue by cxmmxc** [1002326270xc/360Downloading-master#1]
like title

**Comment by cxmmxc** [comment]
`Process: com.single.downloading, PID: 13470
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'long android.graphics.Paint.getNativeInstance()' on a null object reference
                                                                            at android.graphics.Canvas.drawRoundRect(Canvas.java:1251)
                                                                            at com.library.downloading.Down360LoadingView.onDraw(Down360LoadingView.java:247)
                                                                            at android.view.View.draw(View.java:16201)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.draw(View.java:16204)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.draw(View.java:16204)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:283)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:324)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                            at android.os.Handler.handleCallback(Handler.java:742)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

**Comment by cxmmxc** [comment]
```
Process: com.single.downloading, PID: 13470
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'long android.graphics.Paint.getNativeInstance()' on a null object reference
                                                                            at android.graphics.Canvas.drawRoundRect(Canvas.java:1251)
                                                                            at com.library.downloading.Down360LoadingView.onDraw(Down360LoadingView.java:247)
                                                                            at android.view.View.draw(View.java:16201)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.draw(View.java:16204)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15193)
                                                                            at android.view.View.draw(View.java:15971)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
                                                                            at android.view.View.draw(View.java:16204)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:15198)
                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:283)
                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:289)
                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:324)
                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                            at android.os.Handler.handleCallback(Handler.java:742)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by xiangcman** [comment]
已经解决了，主要是由于在mainAcvity中直接使用Down360LoadingView时没初始化画笔导致的，项目中就直接使用Down360ViewGroup吧

**Comment by cxmmxc** [comment]
嗯，我刚也解决了。。。正准备回你呢

**Comment by xiangcman** [comment]
恩恩 好的 有什么好的建议或者想法可以互相讨论
